apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-loadbalancer
  namespace: monitoring
spec:
  ports:
    # Used k describe svc prometheus-stack-grafana -n monitoring to obtain targetPort
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    # Obtain selectors from svc created by Helm Chart
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: grafana
  type: LoadBalancer
