apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homeassistant-loadbalancer
  namespace: homeassistant
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 8123
  selector:
    app: homeassistant
  type: LoadBalancer
