apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-data
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-data-ro
  namespace: homeassistant
spec:
  accessModes:
    # Would set ReadOnlyMany if storage class supported that
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
