config:
  bookmarks:
    - Developer:
      - My Github Repos:
        - abbr: GH
          href: https://github.com/jonathanschwarzhaupt
  services:
    - Household:
      - Mealie:
          href: http://localhost:9000
          description: Let's get cooking
      - Recipes:
          href: https://www.cookwell.com/
          description: Insipration and articles
    - Admin:
      - My admin area:
          href: https://google.com
          description: Go to the internet
