#!/bin/bash

# activate the mise environment
eval "$(mise activate bash)"
# trust the workspace and install
mise trust /workspaces/lab/mise.toml && mise install
# install other tools through mise tasks
mise run install-claude
